"""add_is_likely_fund_column

Revision ID: 09d54e6585a8
Revises: 07b847068977
Create Date: 2026-06-02 21:01:45.002375

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09d54e6585a8"
down_revision: Union[str, Sequence[str], None] = "07b847068977"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "offerings",
        sa.Column("is_likely_fund", sa.Boolean(), nullable=False, server_default=sa.text("0")),
    )
    # Existing rows: is_likely_fund = is_pooled_fund (conservative backfill).
    op.execute("UPDATE offerings SET is_likely_fund = is_pooled_fund")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offerings", "is_likely_fund")
    # ### end Alembic commands ###
