"""baseline schema

Revision ID: 38a43f15c1bb
Revises:
Create Date: 2026-06-02 19:58:48.113798

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38a43f15c1bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filings",
        sa.Column("accession_number", sa.Text(), nullable=False),
        sa.Column("cik", sa.Text(), nullable=False),
        sa.Column("company_name", sa.Text(), nullable=False),
        sa.Column("form_type", sa.Text(), nullable=False),
        sa.Column("date_filed", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.Column("parse_status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("accession_number"),
    )
    op.create_index(op.f("ix_filings_cik"), "filings", ["cik"], unique=False)
    op.create_table(
        "issuers",
        sa.Column("cik", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=True),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("cik"),
    )
    op.create_table(
        "run_log",
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("filings_seen", sa.Integer(), nullable=False),
        sa.Column("filings_stored", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("run_date"),
    )
    op.create_table(
        "offerings",
        sa.Column("accession_number", sa.Text(), nullable=False),
        sa.Column("issuer_name", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("jurisdiction", sa.Text(), nullable=True),
        sa.Column("year_of_incorporation", sa.Text(), nullable=True),
        sa.Column("industry_group", sa.Text(), nullable=True),
        sa.Column("is_pooled_fund", sa.Boolean(), nullable=False),
        sa.Column("total_offering_amount", sa.Numeric(), nullable=True),
        sa.Column("total_amount_sold", sa.Numeric(), nullable=True),
        sa.Column("total_remaining", sa.Numeric(), nullable=True),
        sa.Column("min_investment", sa.Numeric(), nullable=True),
        sa.Column("num_investors", sa.Integer(), nullable=True),
        sa.Column("date_first_sale", sa.Date(), nullable=True),
        sa.Column("is_amendment", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accession_number"],
            ["filings.accession_number"],
        ),
        sa.PrimaryKeyConstraint("accession_number"),
    )
    op.create_table(
        "related_persons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("accession_number", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("relationship", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accession_number"],
            ["filings.accession_number"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_related_persons_accession_number"),
        "related_persons",
        ["accession_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_related_persons_accession_number"), table_name="related_persons")
    op.drop_table("related_persons")
    op.drop_table("offerings")
    op.drop_table("run_log")
    op.drop_table("issuers")
    op.drop_index(op.f("ix_filings_cik"), table_name="filings")
    op.drop_table("filings")
    # ### end Alembic commands ###
